- name: Deploy MERN Quiz App
  hosts: local
  tasks:

    - name: Stop old containers
      shell: docker compose down
      ignore_errors: yes

    - name: Build and start containers
      shell: docker compose up -d --build